CREATE TABLE `media_library` (
	`id` int AUTO_INCREMENT NOT NULL,
	`url` varchar(1000) NOT NULL,
	`filename` varchar(500) NOT NULL,
	`filesize` int,
	`width` int,
	`height` int,
	`mimeType` varchar(50),
	`alt` varchar(500),
	`title` varchar(500),
	`tags` varchar(1000),
	`category` enum('blog','realisations','galerie','produits','ui','og','autre') NOT NULL DEFAULT 'autre',
	`subcategory` varchar(100),
	`sortOrder` int NOT NULL DEFAULT 0,
	`active` boolean NOT NULL DEFAULT true,
	`source` enum('upload_web','upload_cli','migration','external') NOT NULL DEFAULT 'upload_web',
	`uploadedBy` int,
	`usageCount` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `media_library_id` PRIMARY KEY(`id`),
	CONSTRAINT `media_library_url_unique` UNIQUE(`url`)
);
